home/urls.py
from django.urls import path
from home.views import home_view, add_todo, update_todo, delete_todo

app_name = "home"

urlpatterns = [
    path('todo_list/', home_view, name='todo_list'),
    path('add_todo/', add_todo, name='add_todo'),
    path('update_todo/<int:todo_id>/', update_todo, name='update_todo'),
    path('delete_todo/<int:todo_id>/', delete_todo, name='delete_todo'),
] 

project/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls", namespace="home")),
    path('', include("userprofile.urls", namespace="user")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from userprofile.views import UserLoginView, UserSignupView, UserLogoutView

app_name = "user"

urlpatterns = [
	path("login/", UserLoginView.as_view(), name="login"),
	path("register/", UserSignupView.as_view(), name="register"),
	path("logout/", UserLogoutView, name="logout"),

]

home/models.py
from django.db import models
from django.contrib.auth.models import User

#from userprofile.models import Profile

# Create your models here.
#Let's create an object > Todo object
# fields : title , description, date
class Todo(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField(null=True, blank=True)
	date = models.DateField(null=True,blank=True)
	todo_image = models.ImageField(upload_to="upload/todo",blank=True, null=True)
	is_greater_priority = models.BooleanField(default=False)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

	def __str__(self):
		return self.title	
 

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver 
from django.db.models.signals import post_save

# user = User.objects.create_user('john', 'lennon@thebeatles.com', 'johnpassword')

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=255, blank=True)
	middle_name = models.CharField(max_length=255, blank=True)
	last_name = models.CharField(max_length=255, blank=True)
	contact = models.CharField(max_length=255, blank=True)
	address = models.CharField(max_length=255, blank=True)

	def __str__(self):
		return self.first_name	


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

home/forms.py
from django import forms
from home.models import Todo
from django.db.models import fields
from django.contrib.auth.models import User



#class TodoForm(forms.Form):
#	title = forms.CharField()
#	description = forms.CharField()
#	date = forms.DateField()

class TodoForm(forms.ModelForm):
	def __init__(self, *args):
		self.user = args.pop('username', None)
		super(TodoForm, self).__init__(*args)

	def save(self, commit=True):
		obj = super(TodoForm, self).save(commit=False)
		obj.user = self.user
		if commit:
            obj.save()
        return obj



	class Meta:
		model = Todo
		fields = ["title", "description", "date", "todo_image", "is_greater_priority", "user"]

userprofile/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth.forms import User

class CutomAuthenticationForm(AuthenticationForm):
	pass

class CustomUserSignupForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = (
			"username", 
			"email", 
			"password1", 
			"password2"
		)

home/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from home.models import Todo
from home.forms import TodoForm
import datetime
from datetime import date
from django.contrib.auth.models import User


@login_required(login_url='/login/')
def home_view(request):
	users = User.objects.get(id=request.user.id)
	todo = users.todo_set.all()
	context = {"todos" : todo, "user": request.user, "todays_date" : datetime.date.today()}
	return render(request, "todo_list.html", context)

@login_required(login_url='/login/')
def add_todo(request):
	form = TodoForm(request.POST or None, request.FILES or None)
	context = {"form" : form}
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('home:todo_list'))
	return render(request, "form.html", context)

@login_required(login_url='/login/')
def update_todo(request,todo_id):
	todo = get_object_or_404(Todo,id=todo_id)
	form = TodoForm(request.POST or None, request.FILES or None, instance=todo)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('home:todo_list'))
	return render(request, "form.html", {"form" : form, "item_obj" : todo})

@login_required(login_url='/login/')
def delete_todo(request, todo_id):	# passing the request and POST from the delete key in indext.html
	todo = get_object_or_404(Todo, id=todo_id) 	# getting the item ready which was requested with POST method
	if request.method == 'POST':	# this POST is confirm button in the delete.html page which passes through request 
		todo.delete()	# builtin delete function in django models
		return HttpResponseRedirect(reverse("home:todo_list")) # it will redirect to main page of book list after deletion
	return render(request, "delete.html", {"item" : todo})	# rendering to delete.html page, helps to go through html here

userprofile/views.py
from django.shortcuts import reverse, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.views.generic import CreateView
from django.contrib.auth.models import User
from userprofile.forms import  CustomUserSignupForm

class UserLoginView(LoginView):
	template_name = "login.html"
	redirect_authenticated_user = False	
	authentication_form = AuthenticationForm

	def get_success_url(self):
		return reverse("home:todo_list")

def UserLogoutView(request):
	logout(request)
	return redirect(reverse('home:todo_list'))

		

class UserSignupView(CreateView):
	model = User
	form_class = CustomUserSignupForm
	template_name = "signup.html"

	def form_valid(self, form):
		super().form_valid(form)
		user = authenticate(
			username = form.cleaned_data.get("username"), 
			password = form.cleaned_data.get("password1"),
		)
		login(self.request, user)
		return redirect(reverse("home:todo_list"))

	def get_success_url(self):
		return reverse("user:login")

home/templates/add_list.html
{% extends "base.html" %}
{% block content %}

<div class="card-header">
	<div class="container">
 		<div class="row justify-content-center">
			<div class="card text-white bg-dark " style="max-width: 80rem;">
				{% if item_obj %}
					<div class="card-header bg-info text-center">Update Item</div>
					<div class="card-body">
						<form method="POST" action="" enctype="multipart/form-data">
							{% csrf_token %}
							{{ form.as_p }}
							<div class="text-center">			
							<input class="btn btn-primary btn-sm " type="submit" value="Update" >
							</div> 
						</form>
					</div>
				{% else %}
  					<div class="card-header bg-info text-center">Add Item</div>
					<div class="card-body">
						<form method="POST" action="" enctype="multipart/form-data">
							{% csrf_token %}
							<p>Title: {{ form.title }}</p>
							<p>User: {{ request.user }}</p>
							<div class="text-center" >			
							<input class="btn btn-primary btn-sm " type="submit" value="    Add    " >
							</div> 
						</form>
					</div>
  				
				{% endif %}

 			</div>
 		</div>
	</div>
</div>
{% endblock %}

home/templates/delete.html
{% extends "base.html" %}
{% block content %}

<div class="card-header">
	<div class="container">
 		<div class="row justify-content-center">
			<div class="card text-white bg-dark " style="max-width: 60rem;">
  				<div class="card bg-info card-header text-center text-white">Delete Item</div>
  					<div class="card-body">
						<p>Are you sure you want to delete "{{item}}" item?</p>
						<form action=""  method="POST">
							{% csrf_token %}
							<div class="text-center">
								<input class="btn btn-sm btn-primary" type="submit" value="Confirm">
								<a class="btn btn-sm btn-danger text-white" href="{% url 'home:todo_list' %}">Cancel</a>
							</div>
							
						</form>
					</div>
 			</div>
 		</div>
	</div>
</div>

{% endblock content %}

home/templates/form.html
{% extends "base.html" %}
{% block content %}

<div class="card-header">
	<div class="container">
 		<div class="row justify-content-center">
			<div class="card text-white bg-dark " style="max-width: 80rem;">
				{% if item_obj %}
					<div class="card-header bg-info text-center">Update Item</div>
					<div class="card-body">
						<form method="POST" action="" enctype="multipart/form-data">
							{% csrf_token %}
							{{ form.as_p }}
							<div class="text-center">			
							<input class="btn btn-primary btn-sm " type="submit" value="Update" >
							</div> 
						</form>
					</div>
				{% else %}
  					<div class="card-header bg-info text-center">Add Item</div>
					<div class="card-body">
						<form method="POST" action="" enctype="multipart/form-data">
							{% csrf_token %}
							{{ form.as_p }}
							<div class="text-center" >			
							<input class="btn btn-primary btn-sm " type="submit" value="    Add    " >
							</div> 
						</form>
					</div>
  				
				{% endif %}

 			</div>
 		</div>
	</div>
</div>
{% endblock %}

home/templates/todo_list.html
	{% extends "base.html" %}
	{% block content %}
	{% if todos %}
	<div class="card">
  		<div class="card-body">
  			<h4 class=""> Your Todo List
  				<a class="btn btn-dark">Normal</a>
  				<a class="btn btn-warning">past</a>
  				<a class="btn btn-success">Prior</a>
  			<a href="{% url 'home:add_todo' %}" class="float-right btn btn-primary btn-md ">Add Item</a>		
  			</h4>
 		 </div>
	</div>
		{% for obj in todos %}
        	{% if obj.is_greater_priority  and not obj.date < todays_date %}
			<div class="accordion" id="accordionExample">
				<div class="card shadows mt-2 mb-2">
			    <div class="card-header" id="headingThree">	
			      <h4 class="mb-0">
			        <button class="btn btn btn-success btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
			          	<h5>{{ obj.title }} <a  class="btn btn-sm btn-light">{{ obj.date }}</a>
			          		<div class="float-right col-sm-3"> 
				 				<a class="btn btn-secondary btn-sm" href="{% url 'home:update_todo' obj.id %}">Update Todo</a>
				  				<a class="btn btn-danger btn-sm" href="{% url 'home:delete_todo' obj.id %}">Delete</a>
							</div>
			          	</h5><!--<div class="btn btn-sm btn-danger">{{ obj.date }}</div>-->
			        </button>
			      </h4>			          	
			    </div>
			    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
			      <div class="card-body">
			    		{{ obj.description }}
			      </div>
			    </div>
			  </div>
			</div>			
            {% elif obj.date < todays_date %}
			<div class="accordion" id="accordionExample">
				<div class="card shadows mt-2 mb-2">
			    <div class="card-header" id="headingThree">	
			      <h4 class="mb-0">
			        <button class="btn btn btn-warning btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
			          	<h5>{{ obj.title }} <a  class="btn btn-sm btn-light">{{ obj.date }}</a>
			          		<div class="float-right col-sm-3"> 
				 				<a class="btn btn-secondary btn-sm" href="{% url 'home:update_todo' obj.id %}">Update Todo</a>
				  				<a class="btn btn-danger btn-sm" href="{% url 'home:delete_todo' obj.id %}">Delete</a>
							</div>
			          	</h5><!--<div class="btn btn-sm btn-danger">{{ obj.date }}</div>-->
			        </button>
			      </h4>			          	
			    </div>
			    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
			      <div class="card-body">
			    		{{ obj.description }}
			      </div>
			    </div>
			  </div>
			</div>
			{% else %}
			<div class="accordion" id="accordionExample">
				<div class="card shadows mt-2 mb-2">
			    <div class="card-header" id="headingThree">	
			      <h4 class="mb-0">
			        <button class="btn btn btn-dark btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
			          	<h5>{{ obj.title }} <a  class="btn btn-sm btn-light">{{ obj.date }}</a>
			          		<div class="float-right col-sm-3"> 
				 				<a class="btn btn-secondary btn-sm" href="{% url 'home:update_todo' obj.id %}">Update Todo</a>
				  				<a class="btn btn-danger btn-sm" href="{% url 'home:delete_todo' obj.id %}">Delete</a>
							</div>
			          	</h5><!--<div class="btn btn-sm btn-danger">{{ obj.date }}</div>-->
			        </button>
			      </h4>			          	
			    </div>
			    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
			      <div class="card-body">
			    		{{ obj.description }}
			      </div>
			    </div>
			  </div>
			</div>
			{% endif %}
		{% endfor %}
	{% else %}
	<div class="card">
  		<div class="card-body">
  			<h4 class=""> Your Todo List			
  			<a href="{% url 'home:add_todo' %}" class="float-right btn btn-primary btn-md ">Add Item</a>		
  			</h4>
 		 </div>
	</div>
	<div class="alert alert-success" role="alert">
  		<h4 class="alert-heading">No Todos in the list!</h4>
  			<p>Hey there! Your Todo-List is empty. 
  			You can click on above Add Todo button for listing your Todo Activities.</p>
  		<hr>
  		<p class="mb-0">Just add and start using the app for making sure about your todos.</p>
	</div>
	<p><strong></strong></p>
	{% endif %}
	{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>DJANGO</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</head>

<body>
	<div class="container">
		<nav class="navbar navbar-dark bg-dark">

			<a class="navbar-brand" href="{% url 'home:todo_list' %}">Todo App</a>
			{% if user %}
			<div class="col-sm-4">
				{% if user.username %}
  				<a class="float-right btn btn-info btn-lg">Hi! {{ user.username }}</a>  
  				<a class="float-right btn btn-dark btn-lg" href="{% url 'user:logout' %}">Logout</a>  
  			</div>
  			{% else %}
  			<div class="col-sm-12">
  				<a class="float-right btn btn-dark btn-lg" href="{% url 'user:login' %}">Login</a>  
  				<a class="float-right navbar-brand" > Welcome! </a>  
  			</div>	
			{% endif %}

		</nav>
  		{% block content %}

		{% endblock content %}
  		{% else %}				
  			<a class="btn btn-light" type="button" href="{% url 'user:login' %}">Login</a>   
    		<a class="btn btn-light" type="button" href="{% url 'user:register' %}">Register New User</a>   
    	{% endif %}
	</div>
</body>
</html>

userprofile/templates/login.html
{% extends "base.html" %}
{% block content %}

 
<div class="card-header text-center">
<div class="container">
 	<div class="row justify-content-center">
	<div class="card text-center text-white bg-dark " style="max-width: 20rem;">
  		<div class="card-header text-center">Login</div>
  		<div class="card-body">
			<form method="POST" action="">
				{% csrf_token %}
				{{ form.as_p }}
			<div class="checkbox mb-3">
   				<label>
      			<input type="checkbox" value="remember-me"> Remember me
    			</label>
  			</div>
			<div class="">
				<input class="btn btn-primary btn-sm " type="submit" value="Log In">
				<a class="btn btn-danger btn-sm" type="button" href="{% url 'user:register' %}">Register</a> 
			</div>  
			</form>
			</div>
	 	</div>
	 	</div>
	</div>

	</div>
	{% endblock content %}

userprofile/templates/signup.html
{% extends "base.html" %}
{% block content %}

<div class="card-header">
	<div class="container">
 		<div class="row justify-content-center">
			<div class="card text-white bg-dark " style="max-width: 60rem;">
  				<div class="card-header text-center">Register New User</div>
  				<div class="card-body">
					<form method="POST" action="">
						{% csrf_token %}
						{{ form.as_p }}
						<div class="text-center">			
							<input class="btn btn-primary btn-sm " type="submit" value="Sign Up">
						</div>  
					</form>
				</div>
 			</div>
 		</div>
	</div>

</div>

{% endblock content %}